---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supes-fight
  labels:
    app: supes-fight
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: supes-fight
  template:
    metadata:
      labels:
        app: supes-fight
    spec:
      containers:
      - name: supes-fight
        image: fight:latest
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
        livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
        readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10