---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supes-fight
  labels:
    app: supes-fight
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: supes-fight
  template:
    metadata:
      labels:
        app: supes-fight
    spec:
      containers:
      - name: supes-fight
        image: fight:1.2
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
        
