---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supes-hero
  labels:
    app: supes-hero
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: supes-hero
  template:
    metadata:
      labels:
        app: supes-hero
    spec:
      containers:
        - name: supes-hero
          image: hero:1.1
          ports:
            - name: http
              containerPort: 8080
          imagePullPolicy: IfNotPresent
          env:
            - name: QUARKUS_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: supes-hero
                  key: database
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hero-database-secret
                  key: username
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hero-database-secret
                  key: password
