name: Java CI with Maven

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build Heroes with Maven
      run: mvn -B package --file ./microservices/microservices/heroes/pom.xml

    - name: Build Villains with Maven
      run: mvn -B package --file ./microservices/microservices/villains/pom.xml

    - name: Build Fight with Maven
      run: mvn -B package --file ./microservices/microservices/fight/pom.xml